In [1]:
list1 = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(list1)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#fast way to  cfreate an array
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
# ensure when trying  to reate a 2D array it must be a 2 parenthesis
np.zeros((5,5))
#when dealing with arrrays when the output just brings out one bracket
#it means the array is a one dimension array, 
#but when it brings out two brackets, then the array is a 2d array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
arr1 = np.random.rand(5,5)
# rand brings out a uniform dist
#while randn brings out a normal or gaussian
#randint brings out random integers

In [20]:
arr1.max()

0.9811308870474899

In [21]:
arr1.argmax()

9

In [24]:
arr2 = arr1.reshape(25)
arr

array([1, 2, 3])

In [34]:
from numpy.random import randint

In [33]:
ri(0,55,10)

array([52, 44,  3,  7, 28, 24, 18, 35, 28, 23])

In [36]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[2]

2

In [39]:
arr[1:5]= 100

In [40]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr2 = np.arange(1,21).reshape(4,5)

In [44]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
arr3 = arr2[0:3,:-2]
arr3

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])