In [2]:
file = open('source.txt', 'a')
file.write('we are coming')
file.close()

In [4]:
files = open('source.txt', 'r')
print(files.read())

It is not so simple anymore!
we are coming


# Importing data with the Numpy - np.loadtxt() vs np.genfromtxt()

In [1]:
import numpy as np

In [4]:
data = "Lending-Company-Numeric-Data.csv"
lend_data = np.loadtxt(data, delimiter = ',')

In [5]:
lend_data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [12]:
#np.set_printoptions(threshold=np.inf)
#this is used to show the full data set in numpy arrays

In [13]:
lend_data2 = np.genfromtxt(data, delimiter = ',')
print(lend_data2)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [14]:
np.array_equal(lend_data, lend_data2)

True

In [10]:
lend_data == lend_data2

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       ...,
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [19]:
data2 = 'Lending-Company-Numeric-Data-NAN.csv'

In [20]:
lend_load = np.loadtxt(data2)

ValueError: could not convert string to float: '2000;40;365;3121;4241;13621'

In [23]:
lend_load = np.genfromtxt(data2, delimiter=';')
print(lend_load)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


The major difference between using np.loadtxt() and np.genfrom() is that np.loadtxt() would not import a file that contains missing values while np.genfromtxt() would import a file that contains missing values

In [24]:
#loading a data that contains nul values with np.loadtxt() 
lend_load = np.loadtxt(data2, delimiter = ';', dtype = str)
lend_load

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

## Saving files with Numpy using np.save()

In [2]:
import numpy as np
lend_co = np.genfromtxt('Lending-Company-Saving.csv', delimiter =',', dtype = str, max_rows = 10)
print(lend_co)

[['LoanID' 'StringID' 'Product' 'CustomerGender' 'Location' 'Region'
  'TotalPrice']
 ['1' 'id_1' 'Product B' 'Male' 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' 'Male' 'Location 3' '' '16600.0']
 ['3' 'id_3' 'Product C' 'Female' 'Location 5' 'Region 5' '15600.0']
 ['4' 'id_4' 'Product B' 'Male' 'Location 6' 'Region 1' '16600.0']
 ['5' 'id_5' 'Product D' 'Female' 'Location 7' 'Region 2' '20250.0']
 ['6' 'id_6' 'Product B' 'Female' 'Location 10' 'Region 2' '']
 ['7' 'id_7' 'Product A' 'Male' 'Location 11' 'Region 3' '20250.0']
 ['8' 'id_8' 'Product B' 'Male' 'Location 12' 'Region 6' '16600.0']
 ['9' 'id_9' 'Product A' 'Female' 'Location 3' 'Region 3' '22250.0']]


advantages of saving in .npy format
1. it is lighter than a .cv format
2. it is easier to load in numpy

In [28]:
np.save('lending-numpy', lend_co)

### loading data saved as .npy using numpy

In [29]:
saved_data = np.load('lending-numpy.npy' )
print(saved_data)

[['LoanID' 'StringID' 'Product' 'CustomerGender' 'Location' 'Region'
  'TotalPrice']
 ['1' 'id_1' 'Product B' 'Male' 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' 'Male' 'Location 3' '' '16600.0']
 ['3' 'id_3' 'Product C' 'Female' 'Location 5' 'Region 5' '15600.0']
 ['4' 'id_4' 'Product B' 'Male' 'Location 6' 'Region 1' '16600.0']
 ['5' 'id_5' 'Product D' 'Female' 'Location 7' 'Region 2' '20250.0']
 ['6' 'id_6' 'Product B' 'Female' 'Location 10' 'Region 2' '']
 ['7' 'id_7' 'Product A' 'Male' 'Location 11' 'Region 3' '20250.0']
 ['8' 'id_8' 'Product B' 'Male' 'Location 12' 'Region 6' '16600.0']
 ['9' 'id_9' 'Product A' 'Female' 'Location 3' 'Region 3' '22250.0']]


## Using numpy with the savez()
saving with this method saves your file in a compressed zip format

In [31]:
np.savez('lending-numpyZ', saved_data)

In [ ]:
%S = STRING
%D = INTEGERS/DECIMALS
%F = FLOATING POINT

## saving files with numpy using np.savetxt()

In [33]:
np.savetxt('Lending-text-file.txt', saved_data, fmt = '%s',delimiter = ',')

saving data with this format helps wen you want to save your data in different ways, the %s, %d and %f are used to save in different formats 

# WORKING WITH TEXT DATA

### Working with text data and argument specifiers

#### String interpolation using f-strings

In [35]:
name = 'Francis'
car = 'venza'
wives = 3

In [4]:
name = 'francis'
surname = 'utulu' 
age = 24
hobby = 'reading' 
colour = 'blue'

In [6]:
print(f"the name of the yong man is {name} from the family of {surname}. he is {age} years old. he loves {hobby} and his favourite colour is {colour}")

the name of the yong man is francis from the family of utulu. he is 24 years old. he loves reading and his favourite colour is blue


In [44]:
print('The name of the handsome young man is '+name+ ' he has ', wives, 'wives and drives a ', car)

The name of the handsome young man is Francis he has  3 wives and drives a  venza


In [46]:
print(f'The name of the handsome young man is {name}, he has {wives} wives and drives a {car}')

The name of the handsome young man is Francis, he has 3 wives and drives a venza


#### Using the .format method

In [47]:
var = 'The name of the greatest club in th world is {}'
print(var.format('Barcelona'))

The name of the greatest club in th world is Barcelona


In [8]:
intro = "the name of the yong man is {} from the family of {}. he is {} years old. he loves {} and his favourite colour is {}"
print(intro.format('francis', 'utulu', 24, 'reading', 'blue'))

the name of the yong man is francis from the family of utulu. he is 24 years old. he loves reading and his favourite colour is blue


In [49]:
print('The greatest players in the world are {}, {} and {}'.format('Messi','Ronaldo','De bruyne'))

The greatest players in the world are Messi, Ronaldo and De bruyne


#### Using argument specifiers

Here are some of the basic argument specifiers you should know 
%s - String (or any object with astring representation, like numbers)
%d - Integers 
%f - Floating point numbers
%<number of digits>f - Floating point numbers with a fixed amount of digits to the right of the dot.
   

In [52]:
name2 = 'bola' 
print('The name of the boy is %s' %name2)

The name of the boy is bola


In [57]:
age = 24
print('The name of the boy is %s and he is %d years old' %(name2, age))

The name of the boy is bola and he is 24 years old


In [61]:
pi = 3.14159265358793238
print('The value of p is %d' % pi)

The value of p is 3


In [62]:
print('The value of p is %f' % pi)
# by 

The value of p is 3.141593


In [64]:
print('The value of p is %.9f' % pi)
#by puting .(number) f it will give you the number of decimals you want to print

The value of p is 3.141592654


#### Escape characters in python

\n Creating new line

\t Creating a 'tab'or four spaces

 \ "To convert the double quote into a raw character

\ ' To convert the single quote into a raw character

\ \ To convert the backlash into a raw character

In [1]:
print("This text is currently on one line \nbut this would be on the next")

This text is currently on one line 
but this would be on the next


In [111]:
print("Did you notice the \t space between us")

Did you notice the 	 space between us


In [4]:
print("He said in the last meeting \"ÿou all are doing well\" because we are")

He said in the last meeting "ÿou all are doing well" because we are


In [5]:
print('He\'s a  cheat')

He's a  cheat


In [6]:
print("to print on a new line we use \\n")

to print on a new line we use \n


### Using Various String Methods

In [10]:
s = 'price per unit'
s

'price per unit'

In [11]:
s1 = s.replace('price','cost')

In [12]:
s1

'cost per unit'

In [26]:
s1.startswith('cost')

True

In [27]:
s.startswith('price')

True

In [42]:
s1.endswith('unit')

True

In [43]:
s.endswith('per')

False

In [28]:
s1

'cost per unit'

In [105]:
lhist = s1.split()
lhist

['cost', 'per', 'unit']

In [14]:
s1.split(int)

TypeError: must be str or None, not type

In [36]:
type(lhist)

list

In [37]:
l = ['ball', 'corn', 'apple']

In [38]:
# to join elements of a string to form a string we use the .join method
','.join(l)

'ball,corn,apple'

In [40]:
#the character you put in the hyphea is what python will use to join the elements
' '.join(l)

'ball corn apple'

In [44]:
s2 = 'Mr Elon Musk'
s3 = 'brother man'

In [45]:
s3.upper()

'BROTHER MAN'

In [46]:
s2.upper()

'MR ELON MUSK'

In [48]:
s2.lower()

'mr elon musk'

In [49]:
# to give your string a sentence case
s3.capitalize()

'Brother man'

In [50]:
# to capitalize the first letter of every word in our string
s3.title()

'Brother Man'

In [51]:
#rjust() and ljust() for text justification
'Hello'.rjust(10)

'     Hello'

In [52]:
'Hello'.ljust(10)

'Hello     '

In [53]:
'Hello'.center(10)

'  Hello   '

In [54]:
'Hello'.center(15,'*')

'*****Hello*****'

In [59]:
picnic_items = {'sandwiches':4, 'apples':12, 'çups':4, 'cookies':800}
def print_picnic(items_dict, left_width, right_width):
    print('PICNIC ITEMS'.center(left_width + right_width, '-'))
    for key, value in items_dict.items():
        print(f"{key.ljust(left_width,'-')}{str(value).rjust(right_width)}")
        
print_picnic(picnic_items, 20, 6)
print_picnic(picnic_items, 12, 4)

-------PICNIC ITEMS-------
sandwiches----------     4
apples--------------    12
çups----------------     4
cookies-------------   800
--PICNIC ITEMS--
sandwiches--   4
apples------  12
çups--------   4
cookies----- 800


In [60]:
#strip -- remove excess blank spaces
# --- leading and trailing spaces
s4 = '      quarterly earnings report      '
s4.strip()

'quarterly earnings report'

In [66]:
s4.strip(' t')

'quarterly earnings repor'

In [67]:
s4.strip(' rt')

'quarterly earnings repo'

In [68]:
s4.strip(' qt')

'uarterly earnings repor'

In [76]:
s5 = s4.lstrip()

In [77]:
s4.rstrip()

'      quarterly earnings report'

In [78]:
s4.lstrip(' quarterly')

'nings report      '

In [88]:
s6 = s5.strip('quarterly')
s6

' earnings report      '

In [85]:
s7 = s6.strip()
s7

'earnings report'

In [86]:
s7.upper()

'EARNINGS REPORT'

### String Accessors

#### Methods of strings in Pandas series form

In [87]:
import pandas as pd
operational_kpi = pd.Series(['employee satisfaction rating','employee turnover'])
operational_kpi

0    employee satisfaction rating
1               employee turnover
dtype: object

In [89]:
operational_kpi[0].lstrip('employee')

' satisfaction rating'

In [90]:
operational_kpi[1].lstrip('employee')

' turnover'

In [94]:
kpi_series = operational_kpi.str
print(kpi_series)

In [96]:
operational_kpi.str.lstrip('employee')

0     satisfaction rating
1                turnover
dtype: object

In [97]:
kpi_series.lstrip('employee')

0     satisfaction rating
1                turnover
dtype: object

In [98]:
operational_kpi.str.contains('employee')

0    True
1    True
dtype: bool

In [100]:
operational_kpi.str.contains('satisfaction')

0     True
1    False
dtype: bool

In [103]:
'hello world'.upper()

'HELLO WORLD'

In [104]:
'hello world'.upper().isupper()

True