## Pandas Series

### Pandas series: .unique() & nu nique()

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('Location.csv')    #squeeze is used to convert a dataframe to a pandas series
data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [4]:
data = pd.read_csv('Location.csv', squeeze = True) 
data.head()

C:\Users\Utulu\AppData\Local\Temp\ipykernel_4344\724658025.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze = True)


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [5]:
type(data)

pandas.core.series.Series

In [6]:
# ensure you use the .copy() function to creat copies of your data to work with, 
#this is to ensure that no data is lost during manipulation of said data
loc_data = data.copy()

In [7]:
loc_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [8]:
loc_data.describe()   # describe() to have a broad view of your data

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

In [9]:
#top also means mode, i.e the value that repeats itself the most, 
#while freq is the number of times the top repeats its self
#note: a pandas series is a column in our dataframe

In [10]:
loc_data.unique() #shows all the distinct values in the series

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [11]:
loc_data.nunique() # the number of unique values in the series nunique()##

296

### Converting Series to Arrays (.values, .array, .to_numpy())

In [12]:
import numpy as np

In [14]:
prices = pd.Series({'Product A': 22300, 'Product B': 16600, 'Product C': 1700})

In [15]:
prices

Product A    22300
Product B    16600
Product C     1700
dtype: int64

In [16]:
prices.values

array([22300, 16600,  1700], dtype=int64)

In [18]:
type(prices.values)

numpy.ndarray

In [24]:
prices.array

<PandasArray>
[22300, 16600, 1700]
Length: 3, dtype: int64

In [19]:
prices.to_numpy()

array([22300, 16600,  1700], dtype=int64)

In [21]:
type(prices.to_numpy())

numpy.ndarray

In [22]:
# the .values just shows the values in a numpyarray format without converting it.

In [30]:
#to convert the data type from integer to float, 
#by converting from a pandas series to a numpy array 
#we can indicate the new datatype by saying 'dtype = float'
test_array = prices[['Product A', 'Product B']].to_numpy(dtype = 'float')
test_array
#To index multiple values in a series or array, 
#we use double square bracket instead of the normal single square bracket

array([22300., 16600.])

In [31]:
type(test_array[0])

numpy.float64

#### Pandas Series: .sort_values()


In [34]:
numbers = pd.Series([15, 100, 43, 70, 500])
numbers

0     15
1    100
2     43
3     70
4    500
dtype: int64

In [35]:
numbers.sort_values()

0     15
2     43
3     70
1    100
4    500
dtype: int64

In [36]:
numbers.sort_values(ascending = False)

4    500
1    100
3     70
2     43
0     15
dtype: int64

In [56]:
loc_data.sort_values().head(50)

637       Location 1
884       Location 1
465       Location 1
716      Location 10
623      Location 10
56       Location 10
298      Location 10
542      Location 10
329      Location 10
1010     Location 10
522      Location 10
904      Location 10
946      Location 10
14       Location 10
202      Location 10
922      Location 10
912      Location 10
65      Location 101
759     Location 102
232     Location 104
165     Location 104
180     Location 104
1028    Location 105
942     Location 105
474     Location 105
997     Location 106
203     Location 106
224     Location 107
422     Location 108
104     Location 108
493     Location 108
181     Location 109
792      Location 11
657      Location 11
629      Location 11
871      Location 11
1040     Location 11
832      Location 11
968      Location 11
125      Location 11
289      Location 11
920      Location 11
477      Location 11
750      Location 11
231      Location 11
75       Location 11
595     Location 110
101     Locat

In [57]:
loc_data.tail()

1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, dtype: object

In [61]:
loc_data.index.name = 'index'

In [67]:
loc_data.sort_values().head(10)

index
637      Location 1
884      Location 1
465      Location 1
716     Location 10
623     Location 10
56      Location 10
298     Location 10
542     Location 10
329     Location 10
1010    Location 10
Name: Location, dtype: object

In [65]:
type(loc_data)

pandas.core.series.Series

In [68]:
loc_data.sort_index()

index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [69]:
program = pd.Series([10,20,30,40,50,60,70,80,90])

In [70]:
program

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64